package hp.hputilmgt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EligibilityCriteria implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String criteria;
   private double value;
   private java.lang.String condition;
   private java.lang.String id;

   private java.lang.Integer newId;

   public EligibilityCriteria()
   {
   }

   public java.lang.String getCriteria()
   {
      return this.criteria;
   }

   public void setCriteria(java.lang.String criteria)
   {
      this.criteria = criteria;
   }

   public double getValue()
   {
      return this.value;
   }

   public void setValue(double value)
   {
      this.value = value;
   }

   public java.lang.String getCondition()
   {
      return this.condition;
   }

   public void setCondition(java.lang.String condition)
   {
      this.condition = condition;
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.Integer getNewId()
   {
      return this.newId;
   }

   public void setNewId(java.lang.Integer newId)
   {
      this.newId = newId;
   }

   public EligibilityCriteria(java.lang.String criteria, double value,
         java.lang.String condition, java.lang.String id, java.lang.Integer newId)
   {
      this.criteria = criteria;
      this.value = value;
      this.condition = condition;
      this.id = id;
      this.newId = newId;
   }

}