package hp.hputilmgt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PreAuthorization implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String requestType;
   private java.lang.String trackingNumber;
   private java.lang.String creationDate;
   private java.util.Date createdBy;
   private java.lang.String createdByFacility;
   private java.lang.String phoneNumber;
   private java.lang.String nameForNotification;
   private java.lang.String providerIndUrgency;
   private java.lang.String auditDateREceived;
   private java.lang.String attachmentWithRequest;

   public PreAuthorization()
   {
   }

   public java.lang.String getRequestType()
   {
      return this.requestType;
   }

   public void setRequestType(java.lang.String requestType)
   {
      this.requestType = requestType;
   }

   public java.lang.String getTrackingNumber()
   {
      return this.trackingNumber;
   }

   public void setTrackingNumber(java.lang.String trackingNumber)
   {
      this.trackingNumber = trackingNumber;
   }

   public java.lang.String getCreationDate()
   {
      return this.creationDate;
   }

   public void setCreationDate(java.lang.String creationDate)
   {
      this.creationDate = creationDate;
   }

   public java.util.Date getCreatedBy()
   {
      return this.createdBy;
   }

   public void setCreatedBy(java.util.Date createdBy)
   {
      this.createdBy = createdBy;
   }

   public java.lang.String getCreatedByFacility()
   {
      return this.createdByFacility;
   }

   public void setCreatedByFacility(java.lang.String createdByFacility)
   {
      this.createdByFacility = createdByFacility;
   }

   public java.lang.String getPhoneNumber()
   {
      return this.phoneNumber;
   }

   public void setPhoneNumber(java.lang.String phoneNumber)
   {
      this.phoneNumber = phoneNumber;
   }

   public java.lang.String getNameForNotification()
   {
      return this.nameForNotification;
   }

   public void setNameForNotification(java.lang.String nameForNotification)
   {
      this.nameForNotification = nameForNotification;
   }

   public java.lang.String getProviderIndUrgency()
   {
      return this.providerIndUrgency;
   }

   public void setProviderIndUrgency(java.lang.String providerIndUrgency)
   {
      this.providerIndUrgency = providerIndUrgency;
   }

   public java.lang.String getAuditDateREceived()
   {
      return this.auditDateREceived;
   }

   public void setAuditDateREceived(java.lang.String auditDateREceived)
   {
      this.auditDateREceived = auditDateREceived;
   }

   public java.lang.String getAttachmentWithRequest()
   {
      return this.attachmentWithRequest;
   }

   public void setAttachmentWithRequest(java.lang.String attachmentWithRequest)
   {
      this.attachmentWithRequest = attachmentWithRequest;
   }

   public PreAuthorization(java.lang.String requestType,
         java.lang.String trackingNumber, java.lang.String creationDate,
         java.util.Date createdBy, java.lang.String createdByFacility,
         java.lang.String phoneNumber, java.lang.String nameForNotification,
         java.lang.String providerIndUrgency,
         java.lang.String auditDateREceived,
         java.lang.String attachmentWithRequest)
   {
      this.requestType = requestType;
      this.trackingNumber = trackingNumber;
      this.creationDate = creationDate;
      this.createdBy = createdBy;
      this.createdByFacility = createdByFacility;
      this.phoneNumber = phoneNumber;
      this.nameForNotification = nameForNotification;
      this.providerIndUrgency = providerIndUrgency;
      this.auditDateREceived = auditDateREceived;
      this.attachmentWithRequest = attachmentWithRequest;
   }

}