package hp.hputilmgt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PreAuthorizationRequest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Patient Name")
   private java.lang.String patientName;
   @org.kie.api.definition.type.Label("age")
   private java.lang.Integer age;
   @org.kie.api.definition.type.Label("Date Of Birth")
   private java.util.Date dob;
   @org.kie.api.definition.type.Label("Patient Address")
   private java.lang.String patientAddress;
   @org.kie.api.definition.type.Label("Patient City")
   private java.lang.String patientCity;
   @org.kie.api.definition.type.Label("Patient state")
   private java.lang.String state;
   @org.kie.api.definition.type.Label("Provider Id")
   private java.lang.String providerId;
   @org.kie.api.definition.type.Label("ProviderName")
   private java.lang.String providerName;
   @org.kie.api.definition.type.Label("Provider Address")
   private java.lang.String providerAddress;
   @org.kie.api.definition.type.Label("Request Type")
   private java.lang.String requestType;

   @org.kie.api.definition.type.Label("Diagnosis Date")
   private java.util.Date diagnosisDate;

   @org.kie.api.definition.type.Label("Request Date")
   private java.util.Date requestDate;

   @org.kie.api.definition.type.Label(value = "Group Id")
   private java.lang.String groupId;

   @org.kie.api.definition.type.Label(value = "Request Id")
   private java.lang.String requestId;

   public PreAuthorizationRequest()
   {
   }

   public java.lang.String getPatientName()
   {
      return this.patientName;
   }

   public void setPatientName(java.lang.String patientName)
   {
      this.patientName = patientName;
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.util.Date getDob()
   {
      return this.dob;
   }

   public void setDob(java.util.Date dob)
   {
      this.dob = dob;
   }

   public java.lang.String getPatientAddress()
   {
      return this.patientAddress;
   }

   public void setPatientAddress(java.lang.String patientAddress)
   {
      this.patientAddress = patientAddress;
   }

   public java.lang.String getPatientCity()
   {
      return this.patientCity;
   }

   public void setPatientCity(java.lang.String patientCity)
   {
      this.patientCity = patientCity;
   }

   public java.lang.String getState()
   {
      return this.state;
   }

   public void setState(java.lang.String state)
   {
      this.state = state;
   }

   public java.lang.String getProviderId()
   {
      return this.providerId;
   }

   public void setProviderId(java.lang.String providerId)
   {
      this.providerId = providerId;
   }

   public java.lang.String getProviderName()
   {
      return this.providerName;
   }

   public void setProviderName(java.lang.String providerName)
   {
      this.providerName = providerName;
   }

   public java.lang.String getProviderAddress()
   {
      return this.providerAddress;
   }

   public void setProviderAddress(java.lang.String providerAddress)
   {
      this.providerAddress = providerAddress;
   }

   public java.lang.String getRequestType()
   {
      return this.requestType;
   }

   public void setRequestType(java.lang.String requestType)
   {
      this.requestType = requestType;
   }

   public java.util.Date getDiagnosisDate()
   {
      return this.diagnosisDate;
   }

   public void setDiagnosisDate(java.util.Date diagnosisDate)
   {
      this.diagnosisDate = diagnosisDate;
   }

   public java.util.Date getRequestDate()
   {
      return this.requestDate;
   }

   public void setRequestDate(java.util.Date requestDate)
   {
      this.requestDate = requestDate;
   }

   public java.lang.String getGroupId()
   {
      return this.groupId;
   }

   public void setGroupId(java.lang.String groupId)
   {
      this.groupId = groupId;
   }

   public java.lang.String getRequestId()
   {
      return this.requestId;
   }

   public void setRequestId(java.lang.String requestId)
   {
      this.requestId = requestId;
   }

   public PreAuthorizationRequest(java.lang.String patientName,
         java.lang.Integer age, java.util.Date dob,
         java.lang.String patientAddress, java.lang.String patientCity,
         java.lang.String state, java.lang.String providerId,
         java.lang.String providerName, java.lang.String providerAddress,
         java.lang.String requestType, java.util.Date diagnosisDate,
         java.util.Date requestDate, java.lang.String groupId,
         java.lang.String requestId)
   {
      this.patientName = patientName;
      this.age = age;
      this.dob = dob;
      this.patientAddress = patientAddress;
      this.patientCity = patientCity;
      this.state = state;
      this.providerId = providerId;
      this.providerName = providerName;
      this.providerAddress = providerAddress;
      this.requestType = requestType;
      this.diagnosisDate = diagnosisDate;
      this.requestDate = requestDate;
      this.groupId = groupId;
      this.requestId = requestId;
   }

}