package hp.hputilmgt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PreAuthorizationRequest implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public PreAuthorizationRequest() {
    }

}