package hp.hputilmgt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PreAuthorizationRequest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String patientName;
   private java.lang.Integer age;
   private java.util.Date dob;
   private java.lang.String patientAddress;
   private java.lang.String patientCity;
   private java.lang.String state;
   private java.lang.String providerId;
   @org.kie.api.definition.type.Label(value = "ProviderName")
   private java.lang.String providerName;
   private java.lang.String providerAddress;
   private java.lang.String groupIf;
   private java.lang.String rquestId;
   @org.kie.api.definition.type.Label(value = "Request Type")
   private java.lang.String requestType;

   public PreAuthorizationRequest()
   {
   }

   public java.lang.String getPatientName()
   {
      return this.patientName;
   }

   public void setPatientName(java.lang.String patientName)
   {
      this.patientName = patientName;
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.util.Date getDob()
   {
      return this.dob;
   }

   public void setDob(java.util.Date dob)
   {
      this.dob = dob;
   }

   public java.lang.String getPatientAddress()
   {
      return this.patientAddress;
   }

   public void setPatientAddress(java.lang.String patientAddress)
   {
      this.patientAddress = patientAddress;
   }

   public java.lang.String getPatientCity()
   {
      return this.patientCity;
   }

   public void setPatientCity(java.lang.String patientCity)
   {
      this.patientCity = patientCity;
   }

   public java.lang.String getState()
   {
      return this.state;
   }

   public void setState(java.lang.String state)
   {
      this.state = state;
   }

   public java.lang.String getProviderId()
   {
      return this.providerId;
   }

   public void setProviderId(java.lang.String providerId)
   {
      this.providerId = providerId;
   }

   public java.lang.String getProviderName()
   {
      return this.providerName;
   }

   public void setProviderName(java.lang.String providerName)
   {
      this.providerName = providerName;
   }

   public java.lang.String getProviderAddress()
   {
      return this.providerAddress;
   }

   public void setProviderAddress(java.lang.String providerAddress)
   {
      this.providerAddress = providerAddress;
   }

   public java.lang.String getGroupIf()
   {
      return this.groupIf;
   }

   public void setGroupIf(java.lang.String groupIf)
   {
      this.groupIf = groupIf;
   }

   public java.lang.String getRquestId()
   {
      return this.rquestId;
   }

   public void setRquestId(java.lang.String rquestId)
   {
      this.rquestId = rquestId;
   }

   public java.lang.String getRequestType()
   {
      return this.requestType;
   }

   public void setRequestType(java.lang.String requestType)
   {
      this.requestType = requestType;
   }

   public PreAuthorizationRequest(java.lang.String patientName,
         java.lang.Integer age, java.util.Date dob,
         java.lang.String patientAddress, java.lang.String patientCity,
         java.lang.String state, java.lang.String providerId,
         java.lang.String providerName, java.lang.String providerAddress,
         java.lang.String groupIf, java.lang.String rquestId,
         java.lang.String requestType)
   {
      this.patientName = patientName;
      this.age = age;
      this.dob = dob;
      this.patientAddress = patientAddress;
      this.patientCity = patientCity;
      this.state = state;
      this.providerId = providerId;
      this.providerName = providerName;
      this.providerAddress = providerAddress;
      this.groupIf = groupIf;
      this.rquestId = rquestId;
      this.requestType = requestType;
   }

}