package hp.hputilmgt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PreRequestService implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   public PreRequestService()
   {
   }

   public void processRequest(hp.hputilmgt.PreAuthorization preAuthorization)
   {

      java.util.List<hp.hputilmgt.Question> questions = preAuthorization.getQuestions();
      java.util.List<hp.hputilmgt.EligibilityCriteria>  answers = preAuthorization.getEligibilityCriterias();
      answers = new java.util.ArrayList<hp.hputilmgt.EligibilityCriteria>();
      System.out.println("number of questions" + answers.size());
      for (Question q : questions)
      {
            java.lang.String qu = q.getCode();
            java.lang.String an = q.getAnswer();
            hp.hputilmgt.EligibilityCriteria criteria = new hp.hputilmgt.EligibilityCriteria();
            
            if("BMI".equals(qu))
            {
                double vl = java.lang.Double.parseDouble(an);
                criteria.setValue(vl);
            }else{
                criteria.setCondition(an);
            }
            criteria.setCriteria(qu);
            
            
            answers.add(criteria);
            preAuthorization.setEligibilityCriterias(answers);
      }
    System.out.println("number of cretirai" + answers.size());
   }
   
   public void verifyPreviousClaim(hp.hputilmgt.PreAuthorization preAuthorization)
   {
        String trackingNo  = preAuthorization.getTrackingNumber();
        if("CLTEST".equals(trackingNo)){
            preAuthorization.setIsPreviousClaimVerified("claimExits");
           
        }else{
            preAuthorization.setIsPreviousClaimVerified("noClaim");
        }
       
   }

}