package hp.hputilmgt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Queations implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String requestType;
   private java.lang.String questionId;
   @org.kie.api.definition.type.Label("Question Code")
   private java.lang.String code;
   private java.lang.String type;
   private java.lang.String answer;

   private java.lang.String isRequired;

   public Queations()
   {
   }

   public java.lang.String getRequestType()
   {
      return this.requestType;
   }

   public void setRequestType(java.lang.String requestType)
   {
      this.requestType = requestType;
   }

   public java.lang.String getQuestionId()
   {
      return this.questionId;
   }

   public void setQuestionId(java.lang.String questionId)
   {
      this.questionId = questionId;
   }

   public java.lang.String getCode()
   {
      return this.code;
   }

   public void setCode(java.lang.String code)
   {
      this.code = code;
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public java.lang.String getAnswer()
   {
      return this.answer;
   }

   public void setAnswer(java.lang.String answer)
   {
      this.answer = answer;
   }

   public java.lang.String getIsRequired()
   {
      return this.isRequired;
   }

   public void setIsRequired(java.lang.String isRequired)
   {
      this.isRequired = isRequired;
   }

   public Queations(java.lang.String requestType, java.lang.String questionId,
         java.lang.String code, java.lang.String type, java.lang.String answer,
         java.lang.String isRequired)
   {
      this.requestType = requestType;
      this.questionId = questionId;
      this.code = code;
      this.type = type;
      this.answer = answer;
      this.isRequired = isRequired;
   }

}